[tool.bench.frappe-dependencies]
frappe = ">=10.0.0,<17.0.0"

dependencies = [
	"python-magic==0.4.18",
    "boto3>=1.34.0",
    "botocore>=1.34.0",
    "s3transfer>=0.10.0",
    "six>=1.16.0",
    "urllib3<2.0.0"
]
